config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  get 'welcome/index'

  root 'welcome#index'

  resources :categories

  resources :articles do
    resources :comments
  end

  resources :users

  scope :strongbolt do
    strongbolt
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :category, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery prepend: true, with: :exception

  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = current_user.accessible_categories.map(&:articles).flatten.uniq
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def index
    @categories = current_user.accessible_categories
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    if current_user.can?(:update, Strongbolt::Role)
      @users = User.all
    else
      @users = [ current_user ]
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)

      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    if current_user.can?(:create, User)
      params.require(:user).permit(:email, :password, { category_ids: [] })
    else
      params.require(:user).permit(:email, { category_ids: [] })
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_controller_authorization

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, current_user.accessible_categories, :id, :name %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= link_to 'New article', new_article_path %>

<table>
  <tr>
    <th>Category</th>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.category.name %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/list.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @article.category.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@category.errors.count, "error") %> prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= link_to 'New category', new_category_path %>

<table>
  <tr>
    <th>Name</th>
    <th colspan="2"></th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= link_to 'Show', category_path(category) %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category_path(category),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/categories/list.html.erb
<h1>Listing categories</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StrongboltExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
	<div class="container-fluid">
		<ul class="nav navbar-nav">
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Categories', categories_path %></li>
			<li><%= link_to 'Articles', articles_path %></li>
			<li><%= link_to 'Users', users_path %></li>
			<li><%= link_to 'User Groups', user_groups_path %></li>
			<li><%= link_to 'Roles', roles_path %></li>
		</ul>
		<% if signed_in? %>
			<p class="navbar-text navbar-right">Signed in as <%= current_user.email %>. <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'navbar-link' %></p>
		<% end %>
	</div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <% if current_user.can?(:create, User) %>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
  <% end %>

  <p>
    <%= f.label :categories %><br>
    <%= f.collection_select :category_ids, current_user.accessible_categories, :id, :name,
      { selected: @user.category_ids },
      { multiple: true, size: 3 } %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= link_to 'New user', new_user_path %>

<table>
  <tr>
    <th>E-Mail</th>
    <th colspan="2"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/list.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>E-Mail</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>E-Mail:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Articles', controller: 'articles' %>